### PR TITLE
Compatibility with node 0.6.x

### PR DESCRIPTION
**Pull request by RubenVerborgh**
The current discount package is not compatible with node 0.6.x.
This happens because the new `node-waf` builds into `build/Release` instead of `build/default`.

I have update the package in a backwards-compatible way.

### CODE REVIEW

**Comment by sergioramos** [comment]
+1

**Comment by visnup** [comment]
+1

**Comment by soufiane** [comment]
+1

**Comment by chjj** [comment]
+1

just noticed this today.

**Comment by thelastnode** [comment]
+1

**Pull request merged**
